version: '3'
services:
  nuoadmin1:
    image: nuodb/nuodb-ce:latest
    environment:
      NUODB_DOMAIN_ENTRYPOINT: nuoadmin1
    hostname: nuoadmin1
    command: [ "nuoadmin" ]
  sm:
    image: nuodb/nuodb-ce:latest
    hostname: sm
    environment:
      NUOCMD_API_SERVER: nuoadmin1:8888
    depends_on:
      - nuoadmin1
    command: [ "nuodocker", "start", "sm", "--db-name", "hockey", "--server-id", "nuoadmin1", "--dba-user", "dba", "--dba-password", "goalie" ]
  te1:
    image: nuodb/nuodb-ce:latest
    hostname: te1
    environment:
      NUOCMD_API_SERVER: nuoadmin1:8888
    depends_on:
      - nuoadmin1
      - sm
    command: [ "nuodocker", "start", "te", "--db-name", "hockey", "--server-id", "nuoadmin1" ]
  te2:
    image: nuodb/nuodb-ce:latest
    hostname: te2
    environment:
      NUOCMD_API_SERVER: nuoadmin1:8888
    depends_on:
      - nuoadmin1
      - sm
    command: [ "nuodocker", "start", "te", "--db-name", "hockey", "--server-id", "nuoadmin1" ]
  influxdb:
    image: influxdb:1.8
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
      - "8082:8082"
    volumes:
      - ../deploy/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
  nuocd-sm:
    image: nuodb/nuodb-collector:latest
    depends_on:
      - nuoadmin1
      - sm
      - influxdb
    environment:
      INFLUXURL: http://influxdb:8086
      NUOCMD_API_SERVER: nuoadmin1:8888
      NUOCD_HOSTNAME: sm
    pid: 'service:sm'
  nuocd-te1:
    image: nuodb/nuodb-collector:latest
    depends_on:
      - nuoadmin1
      - sm
      - influxdb
    environment:
      INFLUXURL: http://influxdb:8086
      NUOCMD_API_SERVER: nuoadmin1:8888
      NUOCD_HOSTNAME: te1
    pid: 'service:te1'
  nuocd-te2:
    image: nuodb/nuodb-collector:latest
    depends_on:
      - nuoadmin1
      - sm
      - influxdb
    environment:
      INFLUXURL: http://influxdb:8086
      NUOCMD_API_SERVER: nuoadmin1:8888
      NUOCD_HOSTNAME: te2
    pid: 'service:te2'
  grafana:
    image: grafana/grafana:7.5.4
    depends_on:
      - influxdb
    environment:
      - INFLUX_HOST=influxdb
    volumes:
      - ../conf/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
  ycsb-demo:
    image: nuodb/ycsb:latest
    depends_on:
      - te1
      - te2
    environment:
      PEER_ADDRESS: nuoadmin1
      DB_NAME: hockey
      DB_USER: dba
      DB_PASSWORD: goalie
    command: ["/driver/startup.sh"]
