version: '3'
services:
  load:
    image: nuodb/nuodb-ce:latest
    labels:
      - "owner=${USER}"
    command: [ "batch",  "-H", "influxdb", "/data/monitor-20200107-034803.log.gz" ]
    volumes:
      - ../data:/data
      - ../image/batch.py:/opt/nuodb/etc/nuoca/lib/batch.py
      - ../image/batch:/usr/local/bin/batch
networks:
  default:
    driver: bridge
