version: '3'
services:
  load-nuoagent:
    image: nuodb/nuodb-ce:latest
    labels:
      - "owner=${USER}"
    command: [ "batch",  "-o", "http://influxdb:8086", "/data/monitor-20200107-034803.log.gz" ]
    volumes:
      - ../data:/data
      - ../image/batch.py:/opt/nuodb/etc/nuoca/lib/batch.py
      - ../image/batch:/usr/local/bin/batch
  load-nuoadmin:
    environment:
      - PYTHONPATH='/opt/nuodb/drivers:/opt/nuodb/etc/nuoca/lib'
    image: nuodb/nuodb-ce:latest
    labels:
      - "owner=${USER}"
    command: [ "/opt/nuodb/etc/python/nuopython", "/opt/nuodb/etc/nuoca/lib/stats_influx.py", "-o", "http://influxdb:8086", "-d", "nuodb",  "/data/nuoadmin-stats-20200512-134125.gz" ]
    volumes:
      - ../data:/data
      - ../image/stats_influx.py:/opt/nuodb/etc/nuoca/lib/stats_influx.py
networks:
  default:
    driver: bridge
