{{/* vim: set filetype=mustache: */}}
{{/*
Install influx output plugin, if influx is enabled or influx is referenced.
*/}}
{{ if (hasKey .Values.config "nuocd") }}
{{ if not (empty .Values.config.nuocd)  }}
{{ if .Values.config.nuocd.enabled  }}
{{- if and .Values.influxdb (or .Values.influxdb.enabled .Values.influxdb.host) -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-nuocd-influxdb
  namespace: {{ $.Release.Namespace }}
  labels:
     insights-plugins: "influxdb.conf"
data:
  influxdb.conf: |-
    [[ outputs.influxdb ]]
      urls = [ {{ include "insights.influxdb_url" $ | quote }} ]
      database = "telegraf"
      database_tag = "db_tag"
      exclude_database_tag = true
      ## Retention policy to write to. Empty string writes to the default rp.
      retention_policy = ""
      ## Write consistency (clusters only), can be: "any", "one", "quorum", "all"
      write_consistency = "any"
      ## Write timeout (for the InfluxDB client), formatted as a string.
      ## If not provided, will default to 5s. 0s means no timeout (not recommended).
      timeout = "5s"
{{- end }}
{{- range $file, $content := .Values.config.nuocd.plugins }}
{{- if $content }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-nuocd-{{ $file | replace "_" "." | lower }}
  namespace: {{ $.Release.Namespace }}
  labels:
     insights-plugins: "{{ $file }}"
data:
  {{ $file }}.conf: |-
    {{ tpl $content $ | nindent 4}}
{{ end }}
{{ end }}
{{ end }}
{{ end }}
{{- end }}
