config:
  enabled: false
  
grafana:
  enabled: true
  # if adminPassword not specified a default will be generated
  adminPassword: "temenos123"
  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
    portName: service
  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: nginx
    path: /
    hosts:
    - dashboard.local
  persistence:
    enabled: true

influxdb:
  enabled: false

nuoca:
  enabled: false
