config:
  enabled: true
  # dashboards in files/k8s are loaded into
  # /var/lib/grafana/dashboards/k8s (grafana.sidecar.dashboards.folder.k8s)
  dashboards:
    - k8s
  databases:
    # same influxdb server but different database for
    # above dashboards
    - telegraf

grafana:
  enabled: true
  adminPassword: insights
  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
    portName: service
  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: nginx
    path: /
    hosts:
    - dashboard.local
  persistence:
    enabled: true
  # add provider for k8s that looks in folder k8s.
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'k8s'
        orgId: 1
        folder: 'k8s'
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/k8s

influxdb:
  enabled: true

nuoca:
  enabled: true
  nuoadmin:
    host: nuoadmin
    tls:
      enabled: false
